// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {core} from '../models';

export function CheckLogin():Promise<boolean>;

export function ExportLogs(arg1:Array<main.LogEntry>):Promise<string>;

export function GetCities():Promise<Array<Record<string, any>>>;

export function GetDepsByUnit(arg1:string):Promise<Array<Record<string, any>>>;

export function GetHospitalsByCity(arg1:string):Promise<Array<Record<string, any>>>;

export function GetMembers():Promise<Array<core.Member>>;

export function GetSchedule(arg1:string,arg2:string,arg3:string):Promise<Array<Record<string, any>>>;

export function GetTicketDetail(arg1:string,arg2:string,arg3:string,arg4:string):Promise<core.TicketDetail>;

export function GetUserState():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function SaveUserState(arg1:Record<string, any>):Promise<void>;

export function StartGrab(arg1:Record<string, any>):Promise<void>;

export function StartQRLogin():Promise<void>;

export function StopGrab():Promise<void>;

export function StopQRLogin():Promise<void>;

export function SubmitOrder(arg1:Record<string, any>):Promise<core.SubmitOrderResult>;
